# Default configuration for video rendering

# System settings
system:
  cache_dir: "cache" # Path to the cache directory for storing intermediate files
  video_extensions: # List of file extensions to be treated as video files
    - ".mp4"
    - ".mov"
    - ".webm"
    - ".avi"
    - ".mkv"

# Video settings
video:
  width: 1920
  height: 1080
  fps: 30

# Subtitle settings
subtitle:
  font_path: "/usr/share/fonts/opentype/ipafont-gothic/ipag.ttf" # IPAexGothic font path
  font_color: "white"
  font_size: 64
  max_chars_per_line: 25 # Adjust based on font size and video width
  stroke_color: "black"
  stroke_width: 2
  line_spacing_offset_per_line: 64 # Additional vertical offset per line for multi-line text (e.g., same as font_size)
  x: "(w-text_w)/2"
  y: "h-100-text_h/2" # Center text block 100px from bottom, adjusting for total text height

# Voice settings (VOICEVOX defaults)
voice:
  speaker: 1      # Zundamon (Normal)
  speed: 1.0
  pitch: 0.0

# Character settings
characters:
  default_scale: 1.0 # Default character scale (0.0 to 1.0)
  # Default anchor point for character positioning. Available options:
  # top_left, top_center, top_right, middle_left, middle_center, middle_right,
  # bottom_left, bottom_center, bottom_right
  default_anchor: "bottom_center"
  zundamon:
    default_speaker_id: 3 # VOICEVOXのずんだもんのデフォルトID
    voice_styles:
      normal: 3
      whisper: 22
      angry: 7
  metan:
    default_speaker_id: 6 # VOICEVOXの四国めたんのデフォルトID

# BGM settings
bgm:
  path: null # Path to the default background music file (e.g., "assets/bgm/intro.wav")
  volume: 0.5 # Default BGM volume (0.0 to 1.0)
  start_time: 0.0 # Default BGM start time in seconds
  fade_in_duration: 0.0 # Default BGM fade-in duration in seconds
  fade_out_duration: 0.0 # Default BGM fade-out duration in seconds

# Background settings
background:
  default: "assets/bg/default.png"
