# Default configuration for video rendering

# System settings
system:
  cache_dir: "cache"
  video_extensions:
    - ".mp4"
    - ".mov"
    - ".webm"
    - ".avi"
    - ".mkv"
  timeline:
    enabled: true
    format: "md" # Can be "md", "csv", "both", or "none"
  subtitle_file:
    enabled: true
    format: "srt" # Can be "srt", "ass", "both", or "none"

# Video settings
video:
  width: 1920
  height: 1080
  fps: 30
  background_fit: stretch     # stretch | contain | cover | fit_width | fit_height
  # Performance tuning
  auto_tune: true             # Profile initial clips and adjust threads/workers
  profile_first_clips: 4      # Number of clips to profile for auto_tune
  # GPU filters
  gpu_overlay_experimental: false      # Try CUDA overlays even with RGBA (experimental)
  gpu_scale_with_cpu_overlay: true     # Use GPU for background scaling even when overlays are on CPU
  gpu_scale_aggressive: true           # Try GPU scale-only even if smoke test fails (enable explicitly)
  precache_subtitles: true             # Pre-generate subtitle PNGs per scene to reduce jitter
  precache_min_lines: 6                # If precache_subtitles is false, auto-enable when lines >= this
  allow_opencl_overlay_in_cpu_mode: true   # Allow OpenCL overlays even when HW filter mode is 'cpu' (requires smoke OK)
  # 静的オーバーレイが存在しないシーンでベース映像を生成する最小行数（動画背景時）
  # N 行未満ならベース生成をスキップし、背景をシーン単位で一度だけ正規化して各行へ伝搬（重複スケール回避）
  scene_base_min_lines: 6

# Transition settings
transitions:
  wait_padding_seconds: 2.0  # Silence/stillness duration inserted before each transition boundary

# Subtitle settings
subtitle:
  font_path: "/usr/share/fonts/opentype/ipafont-gothic/ipag.ttf" # IPAexGothic font path
  font_color: "white"
  font_size: 64
  max_chars_per_line: 28 # Widen lines (~1.5x) for fewer breaks
  wrap_mode: chars       # Prefer character-based wrapping for CJK text
  stroke_color: "black"
  stroke_width: 2
  background:
    color: "#000000"         # 背景色（RGBA/HTML表記可, `@0.65` などで透過指定）
    opacity: 0.65             # 0.0〜1.0。colorに@指定がある場合はこちらが優先
    radius: 32                # 角丸半径(px)
    padding: {x: 48, y: 28}   # 内側余白(px)。x/y or left/right/top/bottomで細かく指定可
    border_color: "#FFFFFF"   # 枠線色（border_width>0時のみ適用）
    border_width: 0           # 0で枠線なし
    border_opacity: 0.9       # 枠線の透過率(0.0-1.0)
    image: null               # 画像パスを指定すると背景に貼り付けられる
  line_spacing_offset_per_line: 0  # Extra pixels added between lines (kept for backward compatibility)
  line_spacing_multiplier: 1.15    # Multiplier for natural line height (>=1.0)
  text_align: center               # left | center | right
  x: "(w-text_w)/2"
  y: "h-100-text_h/2" # Center text block 100px from bottom, adjusting for total text height
  # 読みの表示方法（インラインマークアップ時）: none | paren
  #   none  -> [本気|マジ] は「本気」、本気{マジ} も「本気」
  #   paren -> [本気|マジ] は「本気（マジ）」、本気{マジ} も「本気（マジ）」
  reading_display: none

# Voice settings (VOICEVOX defaults)
voice:
  speaker_id: 3      # Example: Copetan (normal voice)
  speed: 1.0
  pitch: 0.0

# Character settings
characters:
  default_scale: 1.0 # Default character scale (0.0 to 1.0)
  # Default anchor point for character positioning. Available options:
  # top_left, top_center, top_right, middle_left, middle_center, middle_right,
  # bottom_left, bottom_center, bottom_right
  default_anchor: "bottom_center"
  copetan:
    default_speaker_id: 3 # 例: VOICEVOXでのこぴぺたん通常ボイスID
    voice_styles:
      normal: 3
      whisper: 22
      angry: 7
  engy:
    default_speaker_id: 8 # 例: VOICEVOXでのエンジー通常ボイスID

# BGM settings
bgm:
  path: null # Path to the default background music file (e.g., "assets/bgm/intro.wav")
  volume: 0.5 # Default BGM volume (0.0 to 1.0)
  start_time: 0.0 # Default BGM start time in seconds
  fade_in_duration: 0.0 # Default BGM fade-in duration in seconds
  fade_out_duration: 0.0 # Default BGM fade-out duration in seconds

# Background settings
background:
  default: "assets/bg/default.png"
  fill_color: "#000000"       # Letterbox color applied for contain/fit modes
  anchor: "middle_center"     # Base alignment when padding/cropping backgrounds

# character presist
defaults:
  characters_persist: true
